# Generated by Django 5.1.1 on 2024-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="users",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="skills",
            field=models.ManyToManyField(blank=True, to="users.skill"),
        ),
    ]
