# Generated by Django 5.1.1 on 2024-10-04 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=255, unique=True)),
                ("business_title", models.CharField(max_length=255)),
                (
                    "salary_range_from",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "salary_range_to",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("work_location", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                ("posting_date", models.DateField()),
                ("closing_date", models.DateField()),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
