# Generated by Django 5.1.1 on 2024-10-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="posted_by",
        ),
        migrations.AlterField(
            model_name="job",
            name="business_title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="closing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_id",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="posting_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_range_from",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_range_to",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="work_location",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
